---
# defaults file for docker_registry
# certificates options
docker_registry_name: "registry"
registry_certs_path: "/etc/ssl/certs"
container_address: "{{ docker_registry_name }}:5000"
key_length: "4096"
key_name: "msa"
valid_time: "365"
company_name: "Mirantis Inc"
company_country: "US"

# deployment type
registry_role: "undefined"

#docker
docker_registry_tar: "/opt/docker_private_registry/roles/docker_registry/files/registry.tar"
openssl_tmp_config: "/tmp/openssl.cnf"