- set_fact:
    num_hosts: "{{ groups['elasticsearch_nodes'] | length }}"

#- debug: var=num_hosts

- set_fact:
    is_even: "{{ ( num_hosts | int ) is even }}"

#- debug: var=is_even


- name: PreCheck_NodesNumber
  fail: msg="The number of nodes must be exactly > 3!"
  when: num_hosts | int < 3


- name: PreCheck_Nodes_Count_Is_Odd
  fail: msg="The number of nodes must be odd. {{ num_hosts  }} is even"
  when: is_even