- set_fact:
    cluster_hosts: "{{ play_hosts | join(',') }}"

- debug: var=cluster_hosts

- name: create gluster volume
  gluster_volume:
    state=present
    name=elastic_backups
    bricks="{{ gluster_storage_dir }}"
    cluster="{{ cluster_hosts }}"
    force=yes
    rebalance=no
    transport=tcp
    replicas={{ num_hosts  }}
    options='{storage.owner-uid: 105, storage.owner-gid 108}'
  run_once: true

